# docker-compose.yml
version: "3"

services:
    scylla:
        image: scylladb/scylla:latest
        ports:
            - "9042:9042"
        volumes:
            - scylla-data:/var/lib/scylla
        environment:
            - SCYLLA_CLUSTER_NAME=MessageCluster
            - SCYLLA_DC=dc1
            - SCYLLA_RPC_ADDRESS=0.0.0.0

volumes:
    scylla-data:
